apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namesoace: expense
  labels:   # these are replicaset labels
    app: mysql
    tier: db
    project: expense
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    # these are used to select the pod to create replicas
    matchLabels:
      tier: db
      app: mysql
      project: expense
  # this is pod definition    
  template:
    metadata:
      # these labels belongs to pod    
      labels:
        tier: db
        app: mysql
        project: expense
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    tier: db
    app: mysql
    project: expense
  ports:
  - name: mysql-svc-port
    protocol: TCP
    port: 3360  # service port
    targetPort: 3360  # container port
